name: photosdemo
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'
dependencies:
  #month_year_picker: ^0.2.0+2
  #month_year_picker: ^0.17.0
  month_year_picker: ^0.3.0+1
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  #get:
  get: 4.6.5
  line_icons: ^2.0.3
  animate_do: 3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true







  assets:
    - assets/proo.png
    - assets/sign.jpg
    - assets/signup.jpg
    - assets/reset.png
    #- assets/sssign.jpg
  #   - images/a_dot_ham.jpeg
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
